config/routes.rb
Rails.application.routes.draw do
  root "application#index"
  get 'allCountries' => 'countries#index', as: 'allCountries'
  get 'search', to: "cards/camp_sites#search"

  scope :admin do

    resources :countries do
      resources :regions
      resources :camp_sites
    end

    resources :regions do
      resources :cities
      resources :camp_sites
    end

    resources :cities do
      resources :camp_sites
    end

    resources :camp_sites

  end

  namespace :cards do
    resources :camp_sites, only: [:index]
    resources :countries, only: [] do
      resources :camp_sites, only: [:index]
      resources :regions, only: [] do
        resources :camp_sites, only: [:index]
        resources :cities, only: [] do
          resources :camp_sites, only: [:index]
        end
      end
    end
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campsite.rb
class Campsite < ApplicationRecord

  belongs_to :city, optional: true
  belongs_to :region

  validates :name, presence: true, length: { minimum: 2 }
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2 }

  belongs_to :region

  has_many :campsites, dependent: :nullify

  accepts_nested_attributes_for :campsites

end

app/models/country.rb
class Country < ApplicationRecord
  has_many :regions, dependent: :destroy
  has_many :campsites, through: :regions

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }

  accepts_nested_attributes_for :regions
  attr_accessor :del_confirm
end

app/models/region.rb
class Region < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2 }
  belongs_to :country
  has_many :cities, dependent: :destroy
  has_many :campsites, dependent: :destroy

  accepts_nested_attributes_for :cities, :campsites
  attr_accessor :del_confirm
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    redirect_to cards_camp_sites_path
  end
end

app/controllers/camp_sites_controller.rb
class CampSitesController < ApplicationController

  def index
    @campsites = Campsite.paginate(page: params[:page], per_page: 8)
  end

  def new
    @campsite = Campsite.new
  end

  def show
    @campsite = Campsite.find(params[:id])
  end

  def edit
    @campsite = Campsite.find(params[:id])
  end

  def destroy
    @campsite = Campsite.find(params[:id])
    @campsite.destroy
    redirect_to camp_sites_path
  end

  def create
    @campsite = Campsite.new(campsite_params)

    if @campsite.save
      redirect_to camp_sites_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @campsite = Campsite.find(params[:id])

    if @campsite.update(campsite_params)
      redirect_to camp_site_path(@campsite)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private


  def campsite_params
    res = params.require(:campsite).permit(:name, :city_id, :region_id)
    params[:city_id].nil? ? res : res.merge!({ city_id: params[:city_id], region_id: City.find(params[:city_id]).region_id })
  end

end

app/controllers/cards/camp_sites_controller.rb
class Cards::CampSitesController < CampSitesController

  def index
    @campsites = Campsite.all

    unless params[:country_id].nil?
      @country = Country.find(params[:country_id])
      @campsites = @country.campsites
    end

    unless params[:region_id].nil?
      @region = Region.find(params[:region_id])
      @campsites = @region.campsites
    end

    unless params[:city_id].nil?
      @city = City.find(params[:city_id])
      @campsites = @city.campsites
    end

    @countries = Country.all
    @regions = @country.nil? ? Region.all : @country.regions
    @cities = @region.nil? ? City.all : @region.cities
  end

  def search
    @campsites = Campsite.where("name LIKE ?","%" + params[:q] + "%")
  end


end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.paginate(page: params[:page], per_page: 8)
  end

  def new
    @city = City.new
  end

  def show
    @city = City.find(params[:id])
    @camp_site = Campsite.new
  end

  def edit
    @city = City.find(params[:id])
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to cities_path
  end

  def create

    @city = City.new(city_params)

    if @city.save
      redirect_to cities_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @city = City.find(params[:id])

    if @city.update(city_params)
      redirect_to action: :show
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def city_params
    res = params.require(:city).permit(:name, :region_id)
    params[:region_id].nil? ? res : res.merge!({ region_id: params[:region_id] })
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
    @countries.each do |country|
      next if country.regions.length.zero?

      reg_list = country.regions.inject('') { |lst, p| "#{lst}#{p.name}, " }
      reg_list.chomp!(', ')

      country.del_confirm = "Some regions will be deleted: #{reg_list}"
    end

  end

  def new
    @country = Country.new
  end

  def show
    @country = Country.find(params[:id])
    @region = Region.new
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])

    if @country.update(country_params)
      redirect_to action: :show
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to countries_path
  end

  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to countries_path
    else
      render 'new'
    end
  end

  private

  def country_params
    params.require(:country).permit(:name)
  end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @regions = Region.paginate(page: params[:page], per_page: 5)

    @regions.each do |region|
      next if region.cities.length.zero?

      city_list = region.cities.inject('') { |lst, p| "#{lst}#{p.name}, " }
      city_list.chomp!(', ')

      region.del_confirm = "Some cities will be deleted: #{city_list}"
    end
  end

  def new
    @region = Region.new
  end

  def show
    @region = Region.find(params[:id])
    @city = City.new
  end

  def edit
    @region = Region.find(params[:id])
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    redirect_to regions_path
  end

  def create

    @region = Region.new(region_params)

    if @region.save
      redirect_to regions_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @region = Region.find(params[:id])

    if @region.update(region_params)
      redirect_to action: :show
    else
      render 'edit', status: :unprocessable_entity
    end
  end


  private

  def region_params
    res = params.require(:region).permit(:name, :country_id)
    params[:country_id].nil? ? res : res.merge!({ country_id: params[:country_id] }) #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/camp_sites/edit.html.erb
<h2>Edit campsite</h2>

<%= form_for @campsite,url: camp_site_path(@campsite),method: :patch, remote: true do |f| %>
  <% if @campsite.errors.any? %>
    <% @campsite.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    Description <br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>

  <div>
    <label>Region</label>
    <%= f.collection_select :region_id, Region.all, :id, :name,{},{class: "form-select"} %>
  </div>
  <br/>

  <div>
    <label>City</label>
    <%= f.collection_select :city_id, City.all, :id, :name,{},{class: "form-select"} %>
  </div>
  <br/>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/camp_sites/index.html.erb
<h1>All campsites</h1>

<% @campsites.each do |campsite| %>
  <div class="card">
    <div class="card-body">
      <h5><%=campsite.name %></h5>
      <p><%=campsite.description %></p>
      <hr>
      <p>region: <%=campsite.region.name%></p>

      <p>city: <%= campsite.city.nil? ? "out of city" : campsite.city.name %></p>


      <%= link_to "Edit", edit_camp_site_path(campsite), :class => 'btn btn-warning btn-sm'%>
      <%= link_to "Delete", camp_site_path(campsite), method: :delete,remote: true, data:{confirm: "Are you sure?"},:class => 'btn btn-danger btn-sm'%>
      <%= link_to "More info", camp_site_path(campsite), :class => 'btn btn-primary btn-sm'%>
    </div>
  </div>
<% end %>
<br>
<%= will_paginate @campsites, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>
<hr>

<div class="alert alert-light"><%= link_to "Add new campsite", new_camp_site_path,:class => 'btn btn-outline-primary' %>

</div>

app/views/camp_sites/new.html.erb
<h2>New campsite add</h2>

<%= form_for :campsite, url: camp_sites_path, remote: true do |f| %>
  <% if @campsite.errors.any? %>
    <% @campsite.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    Description <br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>

  <div>
    <label>Region</label>
    <%= f.collection_select :region_id, Region.all, :id, :name,{},{class: "form-select"} %>
  </div>
  <br/>

  <div>
    <label>City</label>
    <%= f.collection_select :city_id, City.all, :id, :name,{:include_blank => "Вне города"},{class: "form-select"} %>
  </div>
  <br/>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/camp_sites/show.html.erb
<br>
<div class="card ">
  <div class="card-body">
    <h3 class="card-title text-center"><%= @campsite.name %></h3>
<hr>
    <div class="card">
      <div class="card-header text-center">
<h5>Description</h5>
      </div>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%=@campsite.description %></p>
      </blockquote>
<hr>
      <ul class="list-group list-group-horizontal " style="width: auto" >

        <!-- Block for Country -->
          <div class="card" style="width: 30rem;">
            <div class="card-header">
              Country
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><%=@campsite.region.country.name %></li>
              <li class="list-group-item "><%= link_to "See all countries", allCountries_path, class: "btn btn-outline-primary btn-sm"  %></li>
            </ul>
          </div>

        <!-- Block for region -->
        <div class="card" style="width: 30rem;">
          <div class="card-header">
            Region
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%=@campsite.region.name %></li>
            <li class="list-group-item"><%= link_to "See all regions", regions_path, class: "btn btn-outline-primary btn-sm" %></li>
          </ul>
        </div>

        <!-- Block for city -->
        <div class="card" style="width: 30rem;">
          <div class="card-header">
            City
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= @campsite.city.nil? ? "out of city" : @campsite.city.name %></li>
            <li class="list-group-item"><%= link_to "See all cities", cities_path, class: "btn btn-outline-primary btn-sm" %></li>
          </ul>
        </div>

      </ul>
      <br>
      <%= link_to "Edit", edit_camp_site_path(@campsite), :class => 'btn btn-warning btn'%>
      <%= link_to "Delete", camp_site_path(@campsite), method: :delete,remote: true, data:{confirm: "Are you sure?"},:class => 'btn btn-danger btn'%>
    </div>
  </div>

  </div>
</div>

app/views/cards/camp_sites/_filters.html.erb
<h5>Filters</h5>
<hr>

<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        Countries
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div class="accordion-body">
        <ul class="list-group">
        <% @countries.each do |country| %>
          <%= link_to country.name, cards_country_camp_sites_path(country) %>
        <% end %>
        <%= link_to "All countries", cards_camp_sites_path %>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        Regions
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body">
        <ul class="list-group">
        <% @regions.each do |region| %>
          <%= link_to region.name, cards_country_region_camp_sites_path(region.country, region)%>
        <% end %>
        <%= link_to "All regions", cards_country_camp_sites_path(@country) unless @country.nil? %>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        Cities
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
        <ul class="list-group">
        <% @cities.each do |city| %>
          <%= link_to city.name, cards_country_region_city_camp_sites_path(city.region.country, city.region, city)%>
        <% end %>
        <%= link_to "All cities", cards_country_region_camp_sites_path(@region.country,@region) unless @region.nil? %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/cards/camp_sites/index.html.erb
<h1>Main info</h1>

<div class="row">
  <div class="col-md-3">
    <div class="shadow bg-body rounded p-3">
      <%= render "filters" %>
    </div>
  </div>

  <div class="col-md-9">
    <% if !@city.nil? %>
      <h3>Campsites in city: <%= @city.name %></h3>
      <br/>
    <% elsif !@region.nil? %>
      <h3>Campsites in region: <%= @region.name %></h3>
      <br/>
    <% elsif !@country.nil? %>
      <h3>Campsites in country: <%= @country.name %></h3>
      <br/>
    <% else %>
      <h3>All campsites</h3>
      <br/>
    <% end %>
    <div class="row">
      <% @campsites.each do |campsite| %>

        <div class="col-md-4">
          <div class="card border-info mb-3">
            <div class="card-header"><h5><%=campsite.name %></h5></div>
            <div class="card-body">
              <p class="card-text"><%=campsite.description %></p>

              <a class="card-link"><a>region: </a> <%=link_to campsite.region.name,cards_country_region_camp_sites_path(campsite.region.country, campsite.region)%></a>
              <br>
              <a class="card-link">
                <%= !campsite.city.nil? ? "<a>city: </a>".html_safe: ""%>
                <%= !campsite.city.nil? ? link_to(campsite.city.name, cards_country_region_city_camp_sites_path(campsite.city.region.country, campsite.city.region, campsite.city)) : ""%>
              </a>

            </div>
          </div>
        </div>
      <% end %>
      </div>
  </div>
</div>
</div>

app/views/cards/camp_sites/search.html.erb
<h1>Search Results</h1>
<br>
<div class="row">
  <% @campsites.each do |campsite| %>

    <div class="col-md-4">
      <div class="card border-info mb-3">
        <div class="card-header"><h5><%=campsite.name %></h5></div>
        <div class="card-body">
          <p class="card-text"><%=campsite.description %></p>

          <a class="card-link"><a>region: </a> <%=link_to campsite.region.name,cards_country_region_camp_sites_path(campsite.region.country, campsite.region)%></a>
          <br>
          <a class="card-link">
            <%= !campsite.city.nil? ? "<a>city: </a>".html_safe: ""%>
            <%= !campsite.city.nil? ? link_to(campsite.city.name, cards_country_region_city_camp_sites_path(campsite.city.region.country, campsite.city.region, campsite.city)) : ""%>
            <br>
            <br>
            <%= link_to "More info", camp_site_path(campsite), :class => 'btn btn-primary btn-sm'%>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cities/edit.html.erb
<h2>Edit city</h2>

<%= form_for :city, url: cities_path(@city), method: :patch, remote: true do |f| %>
  <% if @city.errors.any? %>
    <% @city.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <br>
  <div>
    <label>Region</label>
    <%= f.collection_select :region_id, Region.all, :id, :name,{},{class: "form-select"} %>
  </div>
  <br/>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/cities/index.html.erb
<h1>All cities</h1>

<% @cities.each do |city| %>
  <div class="card">
    <div class="card-body">
      <h5><%=city.name %></h5>
      <p>region: <%=city.region.name %></p>
      <%= link_to "Edit", edit_city_path(city), :class => 'btn btn-warning btn-sm'%>
      <%= link_to "Delete", city_path(city), method: :delete,remote: true, data:{confirm: "Are you sure?"},:class => 'btn btn-danger btn-sm'%>
      <%= link_to "More info", city_path(city), :class => 'btn btn-primary btn-sm'%>
    </div>
  </div>
<% end %>
<hr>
<%= will_paginate @campsites, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>
<br>
<div class="alert alert-light"><%= link_to "Add new city", new_city_path,:class => 'btn btn-outline-primary' %>

</div>

app/views/cities/new.html.erb
<h2>New city add</h2>

<%= form_for :city, url: cities_path, remote: true do |f| %>
  <% if @city.errors.any? %>
    <% @city.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <div>
    <label>Region</label>
    <%= f.collection_select :region_id, Region.all, :id, :name,{},{class: "form-select"} %>
  </div>
  <br/>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/cities/show.html.erb
<h2><strong><%= @city.name %></strong></h2>
<p>region: <%= @city.region.name %></p>
<hr>

<h4>Camp sites in this city</h4>

<% @city.campsites.each do |campsite| %>
  <div class="card text-dark bg-light mb-3" >
    <div class="card-body">
    <h5><%=campsite.name %></h5>
    <%= link_to "More info", camp_site_path(campsite),:class => 'btn btn-outline-primary' %>
    </div>
  </div>
<% end %>
<br>


<h5>Add new campsite</h5>
<%= form_for( [@city, @camp_site],url: city_camp_sites_path(@city), remote: true) do |f| %>
  <p>
    New campsite <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    Description <br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit("Add",{:class => 'btn btn-warning'}) %>
  </p>
<% end %>

app/views/countries/edit.html.erb
<h2>Edit country</h2>

<%= form_for :country, url: country_path(@country), method: :patch, remote: true do |f| %>
  <% if @country.errors.any? %>
    <% @country.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/countries/index.html.erb
<h1>All countries</h1>

<% @countries.each do |country| %>
  <div class="card">
    <div class="card-body">
    <h4><%=country.name %></h4>

    <%= link_to "Edit", edit_country_path(country), :class => 'btn btn-warning btn-sm'%>
    <%= link_to "Delete", country_path(country), method: :delete,remote: true, data:{confirm: "Are you sure? #{country.del_confirm}"},:class => 'btn btn-danger btn-sm'%>
      <%= link_to "More info", country_path(country), :class => 'btn btn-primary btn-sm'%>
    </div>
  </div>
<% end %>
<hr>
<div class="alert alert-light"><%= link_to "Add new country", new_country_path,:class => 'btn btn-outline-primary' %>

</div>

app/views/countries/new.html.erb
<h2>New country add</h2>

<%= form_for :country, url: countries_path, remote: true do |f| %>
  <% if @country.errors.any? %>
    <% @country.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/countries/show.html.erb
<h2><strong><%= @country.name %></strong></h2>

<hr>

<h4>Regions in this country</h4>

<% @country.regions.each do |region| %>
  <div class="card text-dark bg-light mb-3" >
  <div class="card-body">
    <h5><%=region.name %></h5>
    <%= link_to "More info", region_path(region),:class => 'btn btn-outline-primary' %>
  </div>
  </div>
<% end %>
<hr>

  <h5>Add new region</h5>
  <%= form_for([@country, @region], remote: true) do |f| %>
    <p>
      New region <br>
      <%= f.text_field(:name, {:class => 'form-control'}) %>
    </p>

    <p>
      <%= f.submit("Add",{:class => 'btn btn-success'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js' %>
    <%=stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <h4><%= link_to "Main page", cards_camp_sites_path, class: "navbar-brand mb-0 h1" %></h4>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">

          </li>
          <li class="nav-item">
            <a><%= link_to "Countries", allCountries_path, class: "nav-link active" %></a>
          <li class="nav-item">
            <a><%= link_to "Regions", regions_path, class: "nav-link active" %></a>
          </li>
          <li class="nav-item">
            <a><%= link_to "Cities", cities_path, class: "nav-link active" %></a>
          </li>
          <li class="nav-item">
            <a><%= link_to "Camp sites", camp_sites_path, class: "nav-link active" %></a>
          </li>
        </ul>
        <form class="d-flex" action="/search">
          <input class="form-control me-2" name="q" type="search" placeholder="Campsite name" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search </button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container-fluid p-5">
    <%= yield %>
  </div>


</html>

app/views/regions/edit.html.erb
<h2>Edit region</h2>

<%= form_for :region, url: region_path(@region), method: :patch, remote: true do |f| %>
  <% if @region.errors.any? %>
    <% @region.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <br>
  <div>
    <label>Страна</label>
    <%= f.collection_select :country_id, Country.all, :id, :name,{},{class: "form-select"} %>
  </div>
  <br/>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/regions/index.html.erb
<h1>All regions</h1>

<% @regions.each do |region| %>
  <div class="card">
    <div class="card-body">
      <h5><%=region.name %></h5>
      <p>country: <%=region.country.name %></p>
      <%= link_to "Edit", edit_region_path(region), :class => 'btn btn-warning btn-sm'%>
      <%= link_to "Delete", region_path(region), method: :delete,remote: true, data:{confirm: "Are you sure? #{region.del_confirm}"},:class => 'btn btn-danger btn-sm'%>
      <%= link_to "More info", region_path(region), :class => 'btn btn-primary btn-sm'%>
    </div>
  </div>
<% end %>
<br>
<%= will_paginate @regions, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>
<hr>
<div class="alert alert-light"><%= link_to "Add new region", new_region_path,:class => 'btn btn-outline-primary' %>

</div>

app/views/regions/new.html.erb
<h2>New region add</h2>

<%= form_for :region, url: regions_path, remote: true do |f| %>
  <% if @region.errors.any? %>
    <% @region.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%=msg %></div>
    <%end %>
  <%end %>
  <p>
    Name <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <div>
    <label>Country</label>
    <%= f.collection_select :country_id, Country.all, :id, :name,{},{class: "form-select"} %>
  </div>
  <br/>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/regions/show.html.erb
<h2><strong><%= @region.name %></strong></h2>
<p>country: <%=@region.country.name %></p>
<hr>

<h4>Cities in this region</h4>

<% @region.cities.each do |city| %>
  <div class="card text-dark bg-light mb-3" >
    <div class="card-body">
    <h5><%=city.name %></h5>
    <%= link_to "More info", city_path(city),:class => 'btn btn-outline-primary ' %>
    </div>
  </div>
<% end %>
<hr>


<h5>Add new city</h5>
<%= form_for([@region, @city], remote: true) do |f|%>
  <p>
    New city <br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit("Add",{:class => 'btn btn-warning'}) %>
  </p>
<% end %>